add navbar
GSG-G11/Nova pull request #101
Opened 2022-05-19 12:44 UTC by Mahmoud-Ahmad2

Relates #79 
Close #79

2022-05-19 12:45 UTC, Mahmoud-Ahmad2 commented
<img width="1437" alt="Screen Shot 2022-05-19 at 3 42 26 PM" src="https://user-images.githubusercontent.com/80840350/169296242-c4f9062b-46c3-4ad2-a701-8b45fe17b169.png">

2022-05-20 08:26 UTC, Raghad-Mezied requested changes

2022-05-20 08:26 UTC, Raghad-Mezied commented on client/src/App.js
> +import Navbar from './components/Navbar/Navbar';
Name the file index.jsx

2022-05-20 08:26 UTC, Raghad-Mezied commented on client/src/components/Navbar/Navbar.jsx
> +            // must link to profile page
The profile route is ready, you can navigate to it.

2022-05-20 08:26 UTC, Raghad-Mezied commented on client/src/components/Navbar/Navbar.jsx
> +      ]}
Destructure the Item

2022-05-20 08:26 UTC, Raghad-Mezied commented on client/src/components/Navbar/Navbar.jsx
> +            )}
You can render them in one condition

2022-05-20 08:26 UTC, Raghad-Mezied commented on client/src/components/Navbar/Navbar.jsx
> +                </Button>
Why you are using buttons here? check the menu component

2022-05-21 07:14 UTC, Raghad-Mezied requested changes

2022-05-21 07:14 UTC, Raghad-Mezied commented on client/src/components/Navbar/index.jsx
> +              </Dropdown>
Send an image from the back in checkAuth route and use it here.

2022-05-21 16:27 UTC, Raghad-Mezied requested changes

2022-05-21 16:27 UTC, Raghad-Mezied commented on client/src/components/ActiveMembers/index.js
> +        console.log(data);
Remove the console.

2022-05-21 16:27 UTC, Raghad-Mezied commented on .eslintrc.json
> +        "camelcase": "off",
Remove this role and rename your variable with camelcase

2022-05-21 16:27 UTC, Raghad-Mezied commented on client/src/components/Navbar/index.jsx
> +  const { user } = useSelector((state) => state.auth);
Destructure the id and image from the user and you can check the if there is a user from isAuthenticated,

2022-05-22 07:25 UTC, Raghad-Mezied approved these changes

2022-05-22 07:34 UTC, manar-abed approved these changes

2022-05-22 08:58 UTC, abedshamia approved these changes

2022-05-22 08:58 UTC, merged