Create Happy Clients Reviews
GSG-G11/Nova pull request #102
Opened 2022-05-19 15:57 UTC by manar-abed

relates #99
![image](https://user-images.githubusercontent.com/79801554/169344620-9c0cc93c-30d8-4512-9d11-d42a6f8f6b72.png)

2022-05-20 08:09 UTC, Raghad-Mezied requested changes

2022-05-20 08:09 UTC, Raghad-Mezied commented on client/src/components/ClientReviews/index.jsx
> +import bgImg from '../../assets/images/3d1d398e-30b4-4cfa-9b11-10f312ebfab8-removebg-preview.png';
Rename the images

2022-05-21 10:31 UTC, Raghad-Mezied approved these changes

2022-05-21 13:32 UTC, abedshamia approved these changes

2022-05-22 07:38 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-22 07:39 UTC, merged