Create Join us Component
GSG-G11/Nova pull request #103
Opened 2022-05-20 07:21 UTC by manar-abed

relates #100
![image](https://user-images.githubusercontent.com/79801554/169474973-f1b3bef0-b5af-4cae-8cc4-72b11091d545.png)

2022-05-20 08:06 UTC, Raghad-Mezied requested changes

2022-05-20 08:06 UTC, Raghad-Mezied commented on client/src/components/IntreviewerApp/index.jsx
> +import ScreenImg from '../../assets/images/354a3d4a-d2a6-4cc8-8cdd-16bd7a66a18c-removebg-preview.png';
Rename the image

2022-05-21 09:32 UTC, Raghad-Mezied approved these changes

2022-05-21 12:23 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-21 13:33 UTC, abedshamia approved these changes

2022-05-22 07:40 UTC, merged