80 header
GSG-G11/Nova pull request #104
Opened 2022-05-20 16:13 UTC by Mahmoud-Ahmad2

Relates #80  
Close #80

2022-05-20 16:14 UTC, Mahmoud-Ahmad2 commented
<img width="1437" alt="Screen Shot 2022-05-20 at 6 34 56 PM" src="https://user-images.githubusercontent.com/80840350/169569605-098eaa5c-3307-485b-b999-15160e4ab743.png">

2022-05-20 16:53 UTC, Raghad-Mezied requested changes

2022-05-20 16:53 UTC, Raghad-Mezied commented on client/src/components/Header/index.jsx
> +                </Button>
Link these btn

2022-05-20 16:53 UTC, Raghad-Mezied commented on client/src/components/Header/index.jsx
> +        }}
Move the style to the css file

2022-05-20 16:53 UTC, Raghad-Mezied commented on client/src/components/Header/index.jsx
> +            </p>
Check Typography antd component

2022-05-21 04:17 UTC, manar-abed approved these changes

2022-05-21 07:17 UTC, Raghad-Mezied approved these changes

2022-05-21 13:33 UTC, abedshamia approved these changes

2022-05-21 13:33 UTC, merged