81 how nova work
GSG-G11/Nova pull request #106
Opened 2022-05-21 15:53 UTC by Mahmoud-Ahmad2

Relates #81 
Close #81

2022-05-21 15:55 UTC, Mahmoud-Ahmad2 commented
<img width="1422" alt="Screen Shot 2022-05-21 at 6 51 07 PM" src="https://user-images.githubusercontent.com/80840350/169659569-e6563e9d-fea5-4887-b343-188cff7cf2a4.png">

2022-05-21 16:19 UTC, Raghad-Mezied requested changes

2022-05-21 16:19 UTC, Raghad-Mezied commented on client/src/components/HowNovaWork/index.jsx
> +          {arrImg.map((item) => (
Destructure the data you need from the item

2022-05-21 16:19 UTC, Raghad-Mezied commented on client/src/components/HowNovaWork/index.jsx
> +import actIt from '../../assets/images/pexels-pixabay-163064.png';
Rename the image files, and delete unused image

2022-05-21 16:28 UTC, Raghad-Mezied approved these changes

2022-05-22 07:06 UTC, abedshamia approved these changes

2022-05-22 07:35 UTC, manar-abed approved these changes

2022-05-22 07:35 UTC, merged