finish from setup database schemas
GSG-G11/Nova pull request #19
Opened 2022-04-28 17:01 UTC by Mahmoud-Ahmad2

Relates #13
Close #13

2022-04-28 17:39 UTC, Raghad-Mezied requested changes

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/user.ts
> +    required: true,
Email should be unique

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/user.ts
> +  },
Add a default value for the image since the user doesn't upload it with the sign up

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/user.ts
> +  },
You are specified some options for the level, so it is not a num

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/user.ts
> +const userSchema = model('user', user);
Name all the models with the first letter in the capital, like User instead of user

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +        },
The time will be all the available time at this day, so its not a num

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +  },
This should be ref to the user schema

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +        },
Is the type for the date and time a num?

2022-04-28 17:39 UTC, Raghad-Mezied commented on package.json
> +    "env2": "^2.2.2",
Why you needed to install env2 while you already have dotenv

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/config.ts
> +const DB_URL = process.env.DB_URL || 'mongodb://localhost:27017/test';
This URL should depend on the env

2022-04-28 17:39 UTC, Raghad-Mezied commented on server/database/config.ts
> +
Add try and catch and throw an error if there is any problem in connecting to the database. And I think it better to rename it to connectDb

2022-04-28 20:51 UTC, abedshamia approved these changes

2022-04-29 11:52 UTC, Raghad-Mezied approved these changes

2022-04-29 12:17 UTC, manar-abed approved these changes

2022-04-29 12:22 UTC, merged