Create fake data for users and interviews
GSG-G11/Nova pull request #20
Opened 2022-04-28 23:27 UTC by abedshamia

2022-04-29 12:53 UTC, Mahmoud-Ahmad2 approved these changes

2022-04-29 17:45 UTC, Raghad-Mezied requested changes

2022-04-29 17:45 UTC, Raghad-Mezied commented on server/database/fakeData/Users.json
> +            "profile_pic": "https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50",
Its `name` not `full_name`, and `profile_picture` not `profile_pic`

2022-04-29 17:45 UTC, Raghad-Mezied commented on server/database/fakeData/Schedule.json
> +            "language": ["JavaScript", "PHP"],
Its `languages` not `language`, and it is just a string not an array

2022-04-29 17:45 UTC, Raghad-Mezied commented on server/database/fakeData/Schedule.json
> +            "specialization": ["Frontend", "Backend"],
specialization is string not an array

2022-04-29 17:45 UTC, Raghad-Mezied commented on server/database/fakeData/Interviewers.json
> +            "specialization": "Frontend",
Check the options in the schema

2022-04-29 17:45 UTC, Raghad-Mezied commented on server/database/fakeData/Interviewers.json
> +                    "specialization": "Frontend",
Check their options from the schema

2022-04-30 00:09 UTC, abedshamia commented
I couldnt reslove the issues of the enum with the build. Need assistance with it.

2022-04-30 06:35 UTC, Raghad-Mezied requested changes

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/build.ts
> +    console.log(err);
Threw an error here and delete the console.

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/build.ts
> +});
We don't want to invoke this function in the test case, so use `startDb` inside your function and add a condition to invoke `createFakeData`.

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/fakeData/Schedule.json
> +            "languages": "JS, PHP",
This should be a string which means just one value(lang).

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/fakeData/Schedule.json
> +            "specialization": "Frontend, Backend",
The same as languages

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewee.ts
> +          type: [String],
This should be just one lang so its String

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewee.ts
> +          type: [String],
Type String

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewee.ts
> +          enum: ['Technical', 'Behavioural'],
Add these to enum values `Technical, Analytical, Algorithms, System Design`

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +    type: [String],
Type string

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +          type: [String],
type String

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +          type: [String],
type String

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/interviewer.ts
> +          enum: ['Technical', 'Behavioural'],
Edit options here too

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/user.ts
> +    type: [String],
type String

2022-04-30 06:35 UTC, Raghad-Mezied commented on server/database/models/schedule.ts
> +  },
Add options for `languages`, `specialization`, and `questionCategory` in this model.

2022-04-30 10:04 UTC, manar-abed approved these changes

2022-05-01 11:01 UTC, Raghad-Mezied approved these changes

2022-05-01 11:03 UTC, merged