Custom Error and Error Handler
GSG-G11/Nova pull request #23
Opened 2022-04-29 14:55 UTC by abedshamia

- How to use Custom error
```
if(errExample) {
   throw new CustomError( 'message' , code)
}

```

2022-04-29 17:17 UTC, Raghad-Mezied requested changes

2022-04-29 17:17 UTC, Raghad-Mezied commented on server/utils/CustomError/customError.ts
> +export default CustomError;
As you are inside the CustomError folder, then name this file just index.ts, add an index file in the utiles, and import the Custom error from it, not from this file.

2022-04-29 18:34 UTC, Raghad-Mezied requested changes

2022-04-29 18:34 UTC, Raghad-Mezied commented on server/middlewares/errors/errorHandler.ts
> +import CustomError from '../../utils/CustomError';
Import CustomError from the utils(I mean from the index not from the CustomError)

2022-04-29 18:34 UTC, Raghad-Mezied commented on server/middlewares/errors/notFound.ts
> +
The 404 handle error doesn't have 4 parameters, so it just takes req, res, and next parameters.
And this doesn't catch any errors so it doesn't have a code and a message, it just handles the endpoints that we don't handle in our project

2022-04-29 18:40 UTC, Mahmoud-Ahmad2 approved these changes

2022-04-30 01:45 UTC, Raghad-Mezied approved these changes

2022-04-30 10:10 UTC, manar-abed approved these changes

2022-04-30 10:12 UTC, manar-abed approved these changes

2022-04-30 13:28 UTC, merged