14 sign up backend
GSG-G11/Nova pull request #25
Opened 2022-04-30 18:47 UTC by Mahmoud-Ahmad2

Relates #14 
Close #14

2022-04-30 20:50 UTC, Raghad-Mezied requested changes

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +import dotenv from 'dotenv';
You don't need to import `dotenv` here or use we just use it in the connection and in the server.

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    }
Just throw an error and it will be handled in the server error handler.

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    }
If there is no SECRET_KEY, signToken will throw an error.

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    transporter.sendMail(mailOptions, (error: any, info: any) => {
Move all this to a separated file in the utils which sends an email, so we can use it anywhere we need it

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    });
You are sending a response twice, and do we need all these data to send as a response?

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/utils/bcrypt/index.ts
> +const comparePassword = async (password:string, hash:string) => bcrypt.compare(password, hash);
It's a method that you can use directly in your controller, no need to separate them

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/utils/jwt/index.ts
> +const signToken = (payload:string, secret:string) => new Promise((resolve, reject) => {
Do you need to send the secret as an argument? your secret is in the .env which you can reach from here.

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/utils/validation/signUpSchema.ts
> +export default signUpSchema;
When I read signUoSchema I thought it was just the schema and you will do the validate in the controller, so rename this to something more descriptive, and edit the type any.
Also `abortEarly` is by default false so no need to write it.

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/database/queries/signUpUser.ts
> +};
They are all methods so when need them just use them in your controller, you don't need to separate them. We don't need this folder

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +    const { accessToken }: { accessToken?: string } = req.query;
You need to verify the accessToken first, and why do you store it in the database? you already sent the email of this user with the token

2022-04-30 20:50 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +      message: '',
You need to send a message here

2022-04-30 23:19 UTC, abedshamia approved these changes

2022-05-04 10:15 UTC, manar-abed approved these changes

2022-05-07 15:30 UTC, Raghad-Mezied requested changes

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +  }
Just throw an error since all errors will handled in the server middleware.

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +  }
The same as above

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +};
We need to send a token too as we update the user status.
And fix the typo in the message

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/utils/sendEmailVerification/sendEmail.ts
> +
Use async and await instead of the callback

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/utils/validation/signUpCheckInput.ts
> +const signUpCheckInput = async (data: object) => {
Just rename it `signupValidation` so you all have the same style of naming and the same for the file name

2022-05-07 15:30 UTC, Raghad-Mezied commented on server/utils/validation/signUpCheckInput.ts
> +  const result: any = await schema.validateAsync(data, { abortEarly: false });
fix the any type

2022-05-08 16:42 UTC, Raghad-Mezied requested changes

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +      }
There is a folder in the utils for the interfaces, so move this interface to it

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +    const hashedPassword: string = await bcrypt.hash(password, 10);
Destructure the hash method

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +      },
Since we will not use these data in the front, so do you still need to send them?

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/controllers/authentication/signUp.ts
> +const signup = async (req: Request, res: Response) => {
Rename the file to be the same as the function name

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/controllers/authentication/validateEmail.ts
> +  const user = await User.findOne({ email: token.email });
Destructure the email  and the data that you need from the user

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/utils/validation/signupValidation.ts
> +  const result: object = await schema.validateAsync(data, { abortEarly: false });
Since you edit this to abortEarly false, then check the server error middleware and fix the validation error handle

2022-05-08 16:42 UTC, Raghad-Mezied commented on server/tests/routes.test.ts
> +    request(app).post('/api/signup').send({
You still need to test the verify route

2022-05-09 11:49 UTC, Raghad-Mezied approved these changes

2022-05-09 11:49 UTC, merged