add login in frontend
GSG-G11/Nova pull request #27
Opened 2022-05-01 02:49 UTC by Mahmoud-Ahmad2

add login form in modal component in frontend and add axios.post to login in backend

Relates #15
Close #15

2022-05-02 02:54 UTC, abedshamia approved these changes

2022-05-07 16:32 UTC, manar-abed approved these changes

2022-05-08 13:16 UTC, Raghad-Mezied requested changes

2022-05-08 13:16 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +import './Login.css';
As we are already inside the Login folder, then just name the files index.jsx and style.css

2022-05-08 13:16 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +function Demo() {
Edit the Function name to Login

2022-05-08 13:16 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +  };
You received here a message or error from the back so add try and catch and handle them so they appear to the user. And you still need to add the redux logic here

2022-05-08 13:16 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +      </Form.Item>
Destructure the Item and the password

2022-05-08 13:16 UTC, Raghad-Mezied commented on client/src/components/Login/LoginModal.jsx
> +    </>
Move this to a seperated component

2022-05-08 15:53 UTC, Mahmoud-Ahmad2 commented
<img width="539" alt="Screen Shot 2022-05-08 at 6 46 18 PM" src="https://user-images.githubusercontent.com/80840350/167304272-e02c65b1-4e84-4343-a1ce-780cc23b8b22.png">
<img width="539" alt="Screen Shot 2022-05-08 at 6 46 56 PM" src="https://user-images.githubusercontent.com/80840350/167304279-538ebed8-5297-44a
<img width="539" alt="Screen Shot 2022-05-08 at 6 47 10 PM" src="https://user-images.githubusercontent.com/80840350/167304284-a1412557-bc0b-4e23-85e6-b6523818710e.png">
0-af2a-221b1e47634b.png">

2022-05-08 16:21 UTC, Raghad-Mezied requested changes

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/redux/store.js
> +    user: userReducer,
We created the file set up for redux, why you are adding a new one?
You already have the authReducer and the authSlice, so just fill them

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/index.jsx
> +        <img className="logo" src={logo} alt="" />
Add alt for the image

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +    e.preventDefault();
Do you need to prevent the default here and when changing the password? you are not submitting the form here.

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +      const user = await axios.post('/api/login', { email, password });
Destructure the user and the error

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +      dispatch(setUser(user.data.data.user));
We received a message from the backend with a success login so get this message and show it to the user.

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +      setError(err.response.data.message);
Check the message antd component and use it, that you will not need the error state

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/Login.jsx
> +            type: 'email',
split these rules so you have a message for the empty input and another message for invalid email

2022-05-08 16:21 UTC, Raghad-Mezied commented on client/src/components/Login/index.jsx
> +function LoginModal() {
Convert all the functions to the arrow function.
If you edit the file's name so they match the functions components, I mean the Login file is actually the loginModal component.
And I think the components name is confusing, the modal is called just Login and the Login btn is called LoginModal

2022-05-09 11:50 UTC, Raghad-Mezied approved these changes

2022-05-09 11:50 UTC, merged