create checkAuth controller
GSG-G11/Nova pull request #28
Opened 2022-05-01 12:29 UTC by manar-abed

relates #12

2022-05-01 12:33 UTC, Raghad-Mezied requested changes
You need to add the router which handled by this controller

2022-05-01 12:33 UTC, Raghad-Mezied commented on server/controllers/auth/checkAuth.ts
> +  res.status(200).json({ data: userInfo });
Since the default status code is 200, then you don't need to send it

2022-05-04 22:21 UTC, abedshamia approved these changes

2022-05-07 14:39 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-08 13:23 UTC, Raghad-Mezied requested changes

2022-05-08 13:23 UTC, Raghad-Mezied commented on server/controllers/auth/checkAuth.ts
> +const checkAuth = (req: any, res: Response) => {
Use the Request type you did previously.

2022-05-08 13:23 UTC, Raghad-Mezied commented on server/routes/authRoutes.ts
> +router.get('/api/checkAuth', checkAuth);
You need to pass the middleware here

2022-05-08 14:19 UTC, Raghad-Mezied approved these changes

2022-05-08 14:20 UTC, merged