create User Auth Midderlware
GSG-G11/Nova pull request #29
Opened 2022-05-01 13:43 UTC by manar-abed

- create verfiy user fun using joi
- create index file to export it
- create check user middelware

2022-05-01 14:02 UTC, Raghad-Mezied requested changes

2022-05-01 14:02 UTC, Raghad-Mezied commented on server/middlewares/auth/userAuth.ts
> +  const { JWT_SECRET } = req.cookies;
Name it something more descriptive, (maybe token)

2022-05-01 14:02 UTC, Raghad-Mezied commented on server/middlewares/auth/userAuth.ts
> +    res.status(401).json({ message: 'Login First!' });
Use CustamizeError

2022-05-01 14:02 UTC, Raghad-Mezied commented on server/middlewares/auth/userAuth.ts
> +      next();
You received data in checkAuth route from this middleware, so you need to send it here.
Also don't use try and catch and handle it in the server middleware

2022-05-04 22:22 UTC, abedshamia approved these changes

2022-05-07 11:42 UTC, Raghad-Mezied approved these changes

2022-05-07 14:39 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-07 16:05 UTC, merged