Login Backend
GSG-G11/Nova pull request #30
Opened 2022-05-01 15:24 UTC by abedshamia

Validate the incoming request.
Check if the user exists in collection
Compare Password
Check if user is verified
Send back a cookie with a token
Tested login cases

2022-05-01 19:51 UTC, Raghad-Mezied requested changes
Good Job Abedalrahman

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  const validPassword: boolean = await bcrypt.compare(password, user.password);
Destructure the compare.

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  const token: string = sign({ id: user.id }, process.env.JWT_SECRET ?? '', { expiresIn: '1h' });
You are using sign sync, so convert it to promise in the utils and use it here.
And restructure all your variables (JWT_SECRET, id, and is_confirmed)

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  res.cookie('jwt', token, {
Name it token instead of jwt

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  });
Destructure the id, email, and the role. And why do you need to send the token?

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +/* eslint-disable no-unused-vars */
Don't disable `eslint`, solve them

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +import loginValidation from '../utils/validation/loginValidation';
Add the validation in the index and here import it with the CustomError from the index

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  return res.status(200).json({
As 200 is the default we don't need to send it.

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/database/Models/User.ts
> +  is_confirmed: {
Just name it is_verified as Mahmoud did

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/routes/authRoutes.ts
> +const router: any = express.Router();
Edit the any type

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/utils/validation/loginValidation.ts
> +
Edit any type

2022-05-01 19:51 UTC, Raghad-Mezied commented on server/tests/routes.test.ts
> +        return done();
Test if the route set a cookie

2022-05-07 05:53 UTC, Raghad-Mezied requested changes

2022-05-07 05:53 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +  const token: any = await signToken(payload, JWT_SECRET, { expiresIn: '1h' });
As we can access the JWT_SECRET in the utils, then no need to pass it here just use it directly in your function.
And edit the `any` type.

2022-05-07 05:53 UTC, Raghad-Mezied commented on server/controllers/authController.ts
> +export default login;
As we will need other auth controllers so add a folder for them call it auth and inside it, you can put your file.

2022-05-07 05:53 UTC, Raghad-Mezied commented on server/utils/index.ts
>  /* eslint-disable import/prefer-default-export */
You already solve this problem so delete this line

2022-05-07 05:53 UTC, Raghad-Mezied commented on server/database/build.ts
> +/* eslint-disable linebreak-style */
Don't disable `eslint`, and you can use `lint-fix` script to fix all these styles.

2022-05-07 09:41 UTC, manar-abed approved these changes

2022-05-07 10:19 UTC, Raghad-Mezied approved these changes

2022-05-07 14:40 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-07 15:20 UTC, merged