Get User Info ById
GSG-G11/Nova pull request #38
Opened 2022-05-09 07:22 UTC by manar-abed

reates #34

2022-05-09 21:19 UTC, Raghad-Mezied requested changes

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +  const { id } = req.params;
You need to validate the params before

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +const getUserByID = async (req: Request, res: Response) => {
Name it with camelCase => getUserById

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +      profile_picture: user.profile_picture,
Destructure the data that you need from the user, and since the default status code is 200 then no need to send it.

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/routes/userRoutes.ts
> +router.get('/:id', getUserByID);
You still have to test your route

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +  const user : any = await User.findOne({ _id: new ObjectId(id) });
Fix the any type

2022-05-09 21:19 UTC, Raghad-Mezied commented on server/app.ts
> +
We  will not use each route here, we will collect them in the index of the routes

2022-05-10 11:49 UTC, Raghad-Mezied requested changes

2022-05-10 11:49 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +/* eslint-disable camelcase */
Remove this line

2022-05-10 11:49 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +const getUserById = async (req: Request, res: Response) => {
There is a typo in the file name so fix it, and if you name it something else, since the interviews, reviews and info are all user profile.

2022-05-10 11:49 UTC, Raghad-Mezied commented on server/controllers/user/userPofile.ts
> +  res.json({ data: user });
Do we need all this data? here there are the password and emails

2022-05-12 16:29 UTC, Raghad-Mezied approved these changes

2022-05-12 19:57 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-13 10:15 UTC, merged