Create Interview and Send email to both parties
GSG-G11/Nova pull request #40
Opened 2022-05-09 11:04 UTC by abedshamia

2022-05-10 19:18 UTC, Raghad-Mezied requested changes

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/controllers/interview/interviewController.ts
> +  });
Why do you find first and then update ? why not update immediately?
Before updating you need to check if the date and the time are available so we don't have a contradiction.
And we have two collections that contain interviews so we need to update both of them

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/app.ts
> +app.use('/api', interviewRouter);
Move these to the routes folder

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/app.ts
> +app.use('/api', interviewRouter);
Move these to the routes folder

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/controllers/interview/interviewController.ts
> +  mailSender(interviewerEmail, 'Interview Request', `You have a new interview request from ${intervieweeEmail}`);
I think still need to send an email to the interviewer with the same details.

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/controllers/interview/interviewController.ts
> +  mailSender(interviewerEmail, 'Interview Request', `You have a new interview request from ${intervieweeEmail}`);
I think still need to send an email to the interviewer with the same details.

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/controllers/interview/interviewEmailTemplate.ts
> +  specialization: string,
As this is not a controller so move it to the utils

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/controllers/interview/interviewEmailTemplate.ts
> +  specialization: string,
As this is not a controller so move it to the utils

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/tests/routes.test.ts
> +      specialization: 'BACKEND',
Cant, you test the success case?

2022-05-10 19:18 UTC, Raghad-Mezied commented on server/tests/routes.test.ts
> +      specialization: 'BACKEND',
Cant, you test the success case?

2022-05-11 07:33 UTC, abedshamia commented on server/controllers/interview/interviewController.ts
> +};
In case we needed more functions in this controller 😅

2022-05-11 09:52 UTC, Raghad-Mezied commented on server/controllers/interview/interviewController.ts
> +};
We will spit them each controller in a file

2022-05-12 20:05 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-12 20:31 UTC, Raghad-Mezied approved these changes

2022-05-13 12:36 UTC, manar-abed approved these changes

2022-05-13 13:12 UTC, merged