Update the saved property in review
GSG-G11/Nova pull request #45
Opened 2022-05-10 08:01 UTC by abedshamia

2022-05-12 21:32 UTC, Raghad-Mezied requested changes

2022-05-12 21:32 UTC, Raghad-Mezied commented on server/controllers/users/updateSavedReview.ts
> +    data: review,
You are updating here so send a message for a successful update.
And why did you return the old review as a response?

2022-05-12 21:32 UTC, Raghad-Mezied commented on server/controllers/users/updateSavedReview.ts
> +  }
Fix the status code

2022-05-12 21:32 UTC, Raghad-Mezied commented on server/controllers/users/updateSavedReview.ts
> +  const { saved } = review;
Destructure the saved in the previous line.

2022-05-14 12:19 UTC, Raghad-Mezied approved these changes

2022-05-14 15:45 UTC, manar-abed approved these changes

2022-05-14 19:41 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-14 19:45 UTC, merged