Create cancal intrview controller
GSG-G11/Nova pull request #48
Opened 2022-05-11 06:52 UTC by manar-abed

relates #41

2022-05-11 10:47 UTC, Raghad-Mezied requested changes

2022-05-11 10:47 UTC, Raghad-Mezied commented on server/database/Models/Interviewer.ts
> +        is_cancalled: {
fix the typo

2022-05-11 10:47 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  const result = await Interviewee.updateOne({ 'interviews._id': interviewId }, { $set: { 'interviews.is_cancalled': true } });
You can update immediately without finding first and then update

2022-05-11 10:47 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  console.log(interviewId);
Remove the console

2022-05-14 09:29 UTC, Raghad-Mezied requested changes

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +/* eslint-disable space-before-blocks */
Fix this line

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  // use vaildation for params after marge
Use the mongoose validate

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  const { email } = user;
Destructure the email

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  // eslint-disable-next-line max-len
Solve all eslint problems

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/routes/userRoutes.ts
> +router.patch('/:interviewId', userAuth, cancalInterview);
Test your controller

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  if (userInfo){
It will not reach this controller if there is no userInfo so no need for this condition

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  const result = await collectionName.updateOne({ 'interviews._id': interviewId }, { $set: { 'interviews.$.is_cancalled': true } });
You will cancel the interview in both interviewee and interview so no need for the above conditions.

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  await mailSender(email, 'Cancel Interview', `<h1> Cancel Interview </h1>
An email will be sent to both the interviewee and the interviewer

2022-05-14 09:29 UTC, Raghad-Mezied commented on server/controllers/intreview/cancalIntreview.ts
> +  return res.json({ data: result, message: 'Interviews updated successfully' });
Send a message to tell the user that the interview canceled instead of updated

2022-05-25 11:58 UTC, abedshamia approved these changes

2022-05-25 12:15 UTC, Raghad-Mezied approved these changes

2022-05-25 12:15 UTC, merged