Add delete function to delete interview from database
GSG-G11/Nova pull request #49
Opened 2022-05-11 08:50 UTC by Mahmoud-Ahmad2

Relates #43
Close #43

2022-05-12 18:29 UTC, manar-abed approved these changes

2022-05-12 19:25 UTC, Raghad-Mezied requested changes

2022-05-12 19:25 UTC, Raghad-Mezied commented on server/controllers/users/deleteInterview.ts
> +    : res.status(404).json({ message: 'Interview not found' });
Throw an error here.

2022-05-12 19:25 UTC, Raghad-Mezied commented on server/controllers/users/deleteInterview.ts
> +  const { id } = req.params;
Check the validation in this PR https://github.com/GSG-G11/Nova/pull/38

2022-05-12 19:50 UTC, Raghad-Mezied approved these changes

2022-05-13 13:13 UTC, abedshamia approved these changes

2022-05-13 17:22 UTC, merged