4 setup project structure
GSG-G11/Nova pull request #5
Opened 2022-04-26 22:00 UTC by abedshamia

Setup the project (file structure , Eslint, packages and Server setup)

- to install packages run ``` yarn install ```

2022-04-26 22:36 UTC, manar-abed approved these changes

2022-04-27 04:39 UTC, Raghad-Mezied requested changes

2022-04-27 04:39 UTC, Raghad-Mezied commented on .eslintrc.json
> +  },
This `eslint` is for your backend side, where there is a browser env here?

2022-04-27 04:39 UTC, Raghad-Mezied commented on client/README.md
> +This project was bootstrapped with [Create React App](https://github.com/facebook/create-react-app).
Delete this file we don't need it

2022-04-27 04:39 UTC, Raghad-Mezied commented on client/package.json
> +    "@testing-library/user-event": "^13.2.1",
Remove testing libraries, install antd and redux.

2022-04-27 04:39 UTC, Raghad-Mezied commented on client/public/index.html
> +    <!--
Add your logo as an icon here and delete all files and images that we don't need.

2022-04-27 04:39 UTC, Raghad-Mezied commented on package.json
> +    "supertest": "^6.2.2"
Are you sure that installed typescript?

2022-04-27 04:39 UTC, Raghad-Mezied commented on server/app.ts
> +
Use all required middlewares.

2022-04-27 04:39 UTC, Raghad-Mezied commented on server/server.ts
> +  console.log(`Server is running on port ${PORT}`);
we are already inside a server folder do just name it index.ts

2022-04-27 05:06 UTC, Raghad-Mezied requested changes

2022-04-27 05:06 UTC, Raghad-Mezied commented on client/src/index.js
> +import reportWebVitals from './reportWebVitals';
You deleted this file, so remove all imports of deleted files, delete all unneeded code, and make sure the app is running without problems.

2022-04-27 10:28 UTC, Mahmoud-Ahmad2 approved these changes

2022-04-27 16:04 UTC, Raghad-Mezied approved these changes

2022-04-27 16:04 UTC, merged