update profile info
GSG-G11/Nova pull request #53
Opened 2022-05-11 14:31 UTC by Mahmoud-Ahmad2

Relates #44
Close #44

2022-05-11 21:44 UTC, Raghad-Mezied requested changes

2022-05-11 21:44 UTC, Raghad-Mezied commented on server/controllers/users/updateInfo.ts
> +/* eslint-disable camelcase */
Fix this line

2022-05-11 21:44 UTC, Raghad-Mezied commented on server/controllers/users/updateInfo.ts
> +
Is it required to update all data?

2022-05-11 21:44 UTC, Raghad-Mezied commented on server/controllers/users/updateInfo.ts
> +    : res.status(200).json({ message: 'No data updated' });
When the data doesn't update, there is a problem, right? 
If yes, then we need to throw an error here.

2022-05-12 19:20 UTC, Raghad-Mezied approved these changes

2022-05-13 13:13 UTC, abedshamia approved these changes

2022-05-13 13:24 UTC, manar-abed approved these changes

2022-05-13 17:44 UTC, merged