User Info Section
GSG-G11/Nova pull request #54
Opened 2022-05-11 17:00 UTC by abedshamia

- [x] Get user info from api when its ready

- For interviewee
![chrome-capture-2022-4-13](https://user-images.githubusercontent.com/73759748/168292861-0e818884-b2bc-4f81-8d3a-bce2897d8fc2.gif)

- For Interviewer
![chrome-capture-2022-4-13 (1)](https://user-images.githubusercontent.com/73759748/168293068-8852ad60-8c2c-4f74-b705-d945cf7ef831.gif)

2022-05-12 18:28 UTC, manar-abed approved these changes

2022-05-14 09:14 UTC, Raghad-Mezied requested changes

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/App.js
> +     }
This part of the profile will be shown to other users whether it's the user profile or not.

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/Forms/Login/LoginForm.jsx
> +// eslint-disable-next-line react/prop-types
Fix this line

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +        <LoadingSpinner />
Check the antd loading components

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +                  </button>
This will not be shown to all interviewees, just the one who is already in his/her profile.

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +const UserInfo = () => {
Use antd components

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +    if (id) {
This id will come from the param not the store

2022-05-14 09:14 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +    }
You need to cleanup the fetch

2022-05-14 09:17 UTC, Raghad-Mezied requested changes

2022-05-14 09:17 UTC, Raghad-Mezied commented on client/src/components/UserInfo/index.js
> +      axios.get(`/api/user/info/${id}`).then((res) => {
Use async and await

2022-05-15 08:06 UTC, Raghad-Mezied approved these changes

2022-05-15 08:48 UTC, Raghad-Mezied approved these changes

2022-05-15 08:49 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-15 09:54 UTC, merged