Create Static upcoming interviews section
GSG-G11/Nova pull request #56
Opened 2022-05-12 14:16 UTC by abedshamia

![captures_chrome-capture-2022-4-12](https://user-images.githubusercontent.com/73759748/168096061-2c49859d-9606-4daf-87ab-85c594ca288d.png)

2022-05-12 18:52 UTC, Raghad-Mezied requested changes

2022-05-12 18:52 UTC, Raghad-Mezied commented on client/src/App.js
> +import ProfileTabs from './components/ProfileTabs/ProfileTabs';
Since you are already inside a ProfileTabs folder, then just name your files index.jsx and style.css

2022-05-12 18:52 UTC, Raghad-Mezied commented on client/src/components/ProfileTabs/ProfileTabs.js
> +      <Tabs.TabPane tab="Upcoming interviews" key="1" defaultActiveKey className="Tab__header">
Destructure the TabPane from the Tabs.

2022-05-12 18:52 UTC, Raghad-Mezied commented on client/src/components/ProfileTabs/ProfileTabs.js
> +      <Tabs.TabPane tab="Settings" key="3">
Maybe it's better to arrange the tabs `Upcoming interviews` then `Interviews history` then `Reviews` then `Settings.

2022-05-13 13:39 UTC, manar-abed approved these changes

2022-05-14 12:20 UTC, Raghad-Mezied approved these changes

2022-05-14 19:42 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-14 19:46 UTC, merged