Create Reviews Component
GSG-G11/Nova pull request #59
Opened 2022-05-13 00:48 UTC by manar-abed

relats #58

2022-05-16 06:46 UTC, manar-abed commented
![image](https://user-images.githubusercontent.com/79801554/168534609-55da0c68-469c-495b-a8f1-1aba59cb004b.png)

2022-05-17 07:40 UTC, Raghad-Mezied requested changes

2022-05-17 07:40 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +        const { data: { data } } = await axios.get('/api/user/review', { cancelToken: source.token });
Destructure the reviews too

2022-05-17 07:40 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +  }, [reviews]);
Your useEffect changes the reviews and runs when the reviews change?

2022-05-17 07:40 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +      if (savedMsg === 'Successfully updated!') {
Why this condition?

2022-05-17 07:40 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +                  {saved ? <StarFilled /> : <StarOutlined />}
Is the save for all your reviews?

2022-05-17 07:40 UTC, Raghad-Mezied commented on client/yarn.lock
> +=======
Solve the conflicts

2022-05-18 06:54 UTC, Raghad-Mezied requested changes

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/ProfileTabs/style.css
> +    width: 70%;
For this to not affect other styles, so add a class for your container and add these styles to these classes inside your container class.

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +import './review.css';
Name the files index.jsx and style.css as we already inside the Review folder

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +    }
Use the try and catch inside the getReviews function

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +              <Option value="saved">saved</Option>
Don't we have an option for the unsaved reviews?

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +            <Select defaultValue="all" style={{ width: 120 }} value={filterVal} onChange={(value) => setFilterVal(value)}>
Move all inline styles to CSS file

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +      {reviewsArr.length > 0 ? reviewsArr.map((review) => (
Destructure the data you need from the review

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +      )) : (<div className="alert alert-primary"> There is no reviews until now </div>) }
Check the empty antd component.

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/Review/review.jsx
> +            avatar={<Avatar src={review.interviewerImage} alt="Han Solo" />}
Add more descriptive alt

2022-05-18 06:54 UTC, Raghad-Mezied commented on client/src/components/index.js
> +// eslint-disable-next-line import/no-named-as-default
Fix eslint

2022-05-24 17:47 UTC, abedshamia approved these changes

2022-05-24 19:16 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-24 20:11 UTC, merged