Create update setting form
GSG-G11/Nova pull request #60
Opened 2022-05-13 13:37 UTC by manar-abed

relates #57

2022-05-18 07:14 UTC, Raghad-Mezied requested changes

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +      const res = await axios.post('/api/user', {
Destructure the message

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +      const res = await axios.post('/api/user', {
Destructure the message

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +          <Radio.Group value={experenice} onChange={(e) => setExperenice(e.target.value)}>
Destructure the TextArea and group

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +          <Radio.Group value={experenice} onChange={(e) => setExperenice(e.target.value)}>
Destructure the TextArea and group

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +import './setting.css';
Name your files index.jsx and style.css

2022-05-18 07:14 UTC, Raghad-Mezied commented on client/src/components/Setting/Setting.jsx
> +import './setting.css';
Name your files index.jsx and style.css

2022-05-20 16:57 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-20 19:57 UTC, abedshamia approved these changes

2022-05-21 05:14 UTC, merged