Add Static Form with steps functionality
GSG-G11/Nova pull request #61
Opened 2022-05-13 14:16 UTC by abedshamia

![chrome-capture-2022-4-13 (2)](https://user-images.githubusercontent.com/73759748/168302945-ff87c774-6bc3-469a-8df3-3b80da2059af.gif)

2022-05-16 09:18 UTC, Raghad-Mezied requested changes

2022-05-16 09:18 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/Steps/StepFive.jsx
> +            <Typography.Title>
Destructure the title.

2022-05-16 09:18 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/InterviewForm.js
> +      const { data: { data } } = await axios.post('/api/interview/available', {
Why is this route POST, don't we want to get the available dates?

2022-05-16 09:18 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/Hours/index.js
> +// eslint-disable-next-line react/prop-types
Fix all `eslint` problems

2022-05-18 04:29 UTC, Raghad-Mezied requested changes

2022-05-18 04:29 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/InterviewForm.js
> +  const [formData, setFormData] = React.useState({
You already destructured the useState, so just use it.

2022-05-18 04:29 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/InterviewForm.js
> +  }, [loading]);
Why you are manipulating dom here? you have a state and you can directly disable the btn according to your state.

2022-05-18 04:29 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/InterviewForm.js
> +    }
Destructure the message

2022-05-18 04:29 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/InterviewForm.js
> +      const response = await axios.post('/api/interview', {
Destructure the message

2022-05-18 04:29 UTC, Raghad-Mezied commented on client/src/components/Forms/Interview/RadioInput/index.js
> +      {option === 'JS' ? 'JavaScript' : option}
Why this condition? if you want you can edit the database.

2022-05-22 11:11 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-22 11:43 UTC, Raghad-Mezied approved these changes

2022-05-22 11:44 UTC, manar-abed approved these changes

2022-05-22 11:45 UTC, merged