Create Partner Componet
GSG-G11/Nova pull request #98
Opened 2022-05-19 11:22 UTC by manar-abed

![image](https://user-images.githubusercontent.com/79801554/169281899-da5d475e-325b-4ede-9051-8a0b7e62b395.png)

2022-05-20 08:29 UTC, Raghad-Mezied requested changes

2022-05-20 08:29 UTC, Raghad-Mezied commented on client/src/components/Partner/index.jsx
> +import brandImg from '../../assets/images/083adf8b-2a2d-4e54-abf5-05853368fe0e-removebg-preview.png';
Rename the image

2022-05-21 11:05 UTC, Raghad-Mezied approved these changes

2022-05-21 13:32 UTC, abedshamia approved these changes

2022-05-22 07:34 UTC, Mahmoud-Ahmad2 approved these changes

2022-05-22 07:37 UTC, merged